@startuml
left to right direction
skinparam packageStyle rectangle

actor "Recursos Humanos" as RRHH
actor "Motor SBSS" as SYS

rectangle "Sistema Control de Asistencia" {
  usecase "CU-02: Registrar / Editar Personal" as CU02
  usecase "CU-03: Asignar Meta de Horas" as CU03
  usecase "CU-04: Programar Horarios Semanales" as CU04
  usecase "CU-05: Registrar Asistencia Diaria" as CU05
  usecase "CU-06: Calcular Desfase y Tardanzas" as CU06
  usecase "CU-07: Actualizar Barra de Progreso" as CU07
  usecase "CU-08: Aprobar / Rechazar Permiso" as CU08
  usecase "CU-10: Generar Documentos PDF" as CU10
  usecase "CU-Audit: Registrar Historial de Auditoría" as CUAudit
}

RRHH --> CU02
RRHH --> CU04
RRHH --> CU05
RRHH --> CU08
RRHH --> CU10

CU02 <.. CU03 : <<extend>> (Si vínculo es practicante)
CU05 ..> CU06 : <<include>>
CU05 ..> CU07 : <<include>>
CU05 ..> CUAudit : <<include>>
CU02 ..> CUAudit : <<include>>

CU06 --> SYS
CU07 --> SYS
@enduml
